### ISSUE TITLE
RollingEventBufferMode is not available in python binding

### ISSUE THREAD

**Issue by dlzcn** [prophesee-ai/openeb#110]
It is exported as "ClusterMaker", mistake? 

See attached screenshot (OpenEB 4.5.2, SDK 4.5.2, Win11, Python 3.8)
![Screenshot 2024-02-20 120042](https://github.com/prophesee-ai/openeb/assets/37014191/8f908fd7-deae-4232-9889-37b855399cb0)

**Comment by nbourdis-psee** [comment]
Hi Haifeng, indeed this is a mistake in the name used for exposing RollingEventBufferMode in Python, we'll fix this in the next release.
