### ISSUE TITLE
Suggestions on Visual odometry on a Drone

### ISSUE THREAD

**Issue by gyillikci** [prophesee-ai/openeb#114]
Hello,

Our project is based on EVK on a drone for visual odometry. What would be the expected event/second to look for. Our highest priority is to keep the low latency as low as possible.  Any suggestions, for a starting point to keep low latency and Realtime on optimal level would be appreciated.

Best,

Giray

**Comment by leonel-psee** [comment]
Hello Giray, 

There is not yet at Prophesee a full application dedicated to visual odometry. But you can have a look on this [event-based vision ressource](https://github.com/uzh-rpg/event-based_vision_resources?tab=readme-ov-file#visual-odometry--slam) presenting some works on the topic.
However, note that for every work with a Prophesee sensor, one of the main point to reach a low latency is to perfom a good bias tuning, combined to optimal light conditions as well. Please see this page for more details:
https://docs.prophesee.ai/stable/hw/manuals/biases.html#available-biases

Leonel for Prophesee Support
