### ISSUE TITLE
Fixing Windows Stage

### ISSUE THREAD

**Issue by cbernard-psee** [prophesee-ai/openeb#17]
![image](https://user-images.githubusercontent.com/90261474/133279039-c40dead6-ac5d-4d61-8098-e55706f76181.png)

8 tests are still failing because compute node memory is not capable of handling current unit tests properly. 
New SW delivery is needed here to reduce the size allocated by unit tests so they are compatible with github runners memory constraints:

For details on memory limits, see here:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by laurentbristiel** [comment]
working ok now
