### ISSUE TITLE
[Modification request] Remove rules installation from project installation

### ISSUE THREAD

**Issue by homalozoa** [prophesee-ai/openeb#52]
Hey! 

Happy to see you opened source code of plugins. For a long time, to install plugins in different CPU architectures platforms are annoyed me. I'm trying use openeb in my robot project. But I found the installation scripts are not allowd me to install this without root privilege because of the `USB rules` installation [hal_psee_plugins/resources/rules/CMakeLists.txt](https://github.com/prophesee-ai/openeb/blob/main/hal_psee_plugins/resources/rules/CMakeLists.txt).

AFAIK. The rules are usually installed independently with shell scripts, like [setup_udev_rules.sh](https://github.com/IntelRealSense/librealsense/blob/master/scripts/setup_udev_rules.sh) in librealsense project. So perhaps create a new file for rules installation is a better idea?

**Comment by nonifier** [comment]
Hey @homalozoa ,

Thanks for your feedback. It's always good to hear from our users :) 

I can imagine needing root privileges to install the suite can be cumbersome. Although, I wonder how you handle the installation of your udev rules on your system ? Since they have to end up in your `/etc/udev/rules.d` folder, you'll require root privilege anyway ?

**Comment by homalozoa** [comment]
Hey @nonifier . Thanks for your reply.

The udev rules' installation always require root privilege, I usually create a shell scripts and run it with `sudo`. It is a part of environment deployment, and it should be distinguished from package installation. Not all package installation destinations are sys directories, such as `/usr/`, /usr/local/`, `/opt/`. etc. Sometimes we install package in $home dirs, like `~/.local`, or any customized folders. Especially working with ROS/ROS 2, we always create a new dir named `workspace` or `ws`, and all outputs of projects under this dir are installed in this dir. That's good for output management. The outputs include files of installation, like binaries, static/dynamic libraries, C++ headers, Python importing libraries, CMake files, etc. They also include building in-process files and logs, too.

**Comment by nonifier** [comment]
If you want to relocate the installation package into a different folder (eg. ~/.local, or any custom workspace), can't you just use Cmake  [DESTDIR](https://cmake.org/cmake/help/latest/envvar/DESTDIR.html#envvar:DESTDIR) ?

**Comment by homalozoa** [comment]
Yes. This is exactly what I am using. But udev rules are not managed under `DESTDIR` or `CMAKE_INSTALL_PREFIX`, that's why I created this issue.

**Comment by nonifier** [comment]
I'm not sure I understand what you mean by "not managed" as the udev rules can be found in the `$DESTDIR/etc/udev/rules.d`folder.

`CMAKE_INSTALL_PREFIX` will not help you much indeed, because of the absolute path being used. But perhaps, that is what you wanted to use in the first place ?

**Comment by homalozoa** [comment]
Oh, sorry. I've confused about `DESTDIR` and `CMAKE_INSTALL_PREFIX`. I just learned about `DESTDIR`, it will prepend directory to default directory. I don't think it's a good idea. Udev rules are devices configuration in system. They should not be put in other dirs. But binaries, headers and libraries are not, they could be anywhere if we want. Hince I think we should use a script to install all udev rules, rather than a CMake file.

**Comment by nonifier** [comment]
If we make the udev system installation rules optional. Would that help ? (as per. https://github.com/prophesee-ai/openeb/compare/main...feature/relax-udev-rules-installation)
We'll leave it to the user to decide how/when to copy the rules on its system.

**Comment by homalozoa** [comment]
Yeah! I think it's a good idea! Then users will enable/disable udev rules installation by using -D options. Thanks!

**Comment by nonifier** [comment]
The change should come in the next minor version (v3.0.2) which will be released in the coming days. 
Thanks again for your feedback !
