### ISSUE TITLE
what's the meanning of the function "make_moving_edgelet_in_time_surface" 

### ISSUE THREAD

**Issue by zebrajiahao** [prophesee-ai/openeb#7]
I learned the metavision_edgelet_2d_tracking, and want to know how this function work? 
Such as the formulation is to do in the below pic:
![Screenshot from 2021-08-28 18-31-23](https://user-images.githubusercontent.com/37396275/131215214-5744774b-bc46-48c1-9d31-db0bfd440c4f.png)

Some papers could be suggested to read.
Looking forward to your reply,Thx.

**Comment by laurentbristiel** [comment]
Hello,
the function you are refering to is not part of OpenEB but part of [Metavision Professional](https://www.prophesee.ai/metavision-intelligence-professional-request/) so I assume you are a Prophesee Customer using this Pro code. If so, you are granted some support in your package and can contact support@prophesee.ai for your question.
If your context is different, please explain it.

**Comment by laurentbristiel** [comment]
We had no feedback from you and the code you shared is private, so I am deleting this issue to not expose copyrighted code.
Please contact us again if you need support but don't shre publicly copyrighted code.
