### ISSUE TITLE
DVS128 Gesture with SilkyCam

### ISSUE THREAD

**Issue by aitsam12** [prophesee-ai/openeb#76]
I am trying to implement DVS128 Gesture classification with SilkyCam.

My model has been trained with 128x128 (DVS128) inputs. SilkyCam receives input in the form of 120x160, 240x320, and 480x640. When I give input from my SilkyCam, it doesn't classify even though the accuracy of my model is 92%. I trained my model with SpikingJelly and then converted it to torch script.
What could be the possible solution for this issue?  

If you are a Metavision SDK customer, you are also granted access to our personal support and our Knowledge Center. Contact us via support@prophesee.ai

**Comment by leonel-psee** [comment]
Hello @aitsam12 
For your issue, do you already think to resize the frame you generate with events from the SilkyEVCam, before sending them to your model taking 128x128 as image size ?

Actually some use cases are shown here with the function resize() in OpenCV and Pillow: https://cloudinary.com/guides/bulk-image-resize/python-image-resize-with-pillow-and-opencv
