### ISSUE TITLE
Path to hdf5 plugin Linux installation

### ISSUE THREAD

**Issue by FriedhelmHamann** [prophesee-ai/openeb#96]
This is regarding linux installation, Option 2 - deploying in the system path:
at least on my system the hdf5 plugin path is
`/usr/local/lib/hdf5/plugin`
not
`/usr/local/hdf5/lib/plugin`

**Comment by lbristiel-psee** [comment]
indeed, this is a typo in the doc.
We will fix it in the next release that should be out very soon.
Thanks @FriedhelmHamann !
